project:
  type: website
  title: INKE-2026
  preview:
    port: 7777
    browser: false
  render:
    - "*.qmd"
    - "!notes/"

website:
  title: "INKE-2026"
  site-url: https://zackbatist.info/inke-2026/
  repo-url: https://github.com/zackbatist/inke-2026
  repo-actions: none
  bread-crumbs: true
  page-navigation: false
  back-to-top-navigation: false

bibliography: assets/inke-2026.bib
csl: assets/chicago-author-date.csl
license: CC0
lang: en-CA

citation:
  type: speech
  event-place: Université de Montréal
  event-title: INKE 2026 Gathering
  doi: TBD
  url: https://zackbatist.info/inke-2026
